
services:
  web:
    build:
      context: build/debug/
      dockerfile: ../../compose/local/Dockerfile
    image: ${DOCKER_IMAGE_TAG}

    ports:
      - "8008:8008"
    volumes:
     - ./src:/sopds-ng
     - ./pytest.ini:/sopds/pytest.ini
     - ${SOPDS_BOOK_PATH}:/books:ro
     - ./.env:/sopds-ng/.env
     - ./bootstrap.sh:/sopds-ng/bootstrap.sh
 #   environment:
 #     DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
 #     DEBUG: ${DEBUG}
 #     SECRET_KEY: ${SECRET_KEY}
    depends_on:
    - db


  db:
    image: postgres:17
    restart: always
    shm_size: 128 mb
    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: ${SOPDS_DB_PASSWORD}
      POSTGRES_DB: 'sopds'
    volumes:
      - sopds-ng-db:/var/lib/postgresql/data/

  mc:
    image: memcached:1.6-alpine
    command:
      - --conn-limit=64
      - --memory-limit=64
      - --threads=2

volumes:
   sopds-ng-db:

